'use strict';
const realtimeExport=$('exportBtn').onclick;let activeExportWorker=null,workerReject=null;
function mediaWorker(type,state){return new Promise((resolve,reject)=>{const worker=new Worker('./export-worker.js?v=20261006-teaching1',{type:'module'});activeExportWorker=worker;workerReject=reject;worker.onmessage=({data})=>{if(data.type==='precheck'){if(!data.audio.present)$('exportChecks').textContent+='\n提醒：來源影片沒有音軌。';else if(data.audio.sampled&&data.audio.peak<.0001)$('exportChecks').textContent+='\n提醒：抽查片段未偵測到聲音。';return}if(data.type==='progress'){$('progress').value=data.value;$('exportStatus').textContent=`背景匯出 ${Math.round(data.value)}% · 可切換分頁，請勿關閉網站或讓電腦睡眠`;return}worker.terminate();if(activeExportWorker===worker){activeExportWorker=null;workerReject=null}if(data.type==='error')reject(Error(data.message));else resolve(data)};worker.onerror=e=>{worker.terminate();activeExportWorker=null;workerReject=null;reject(Error(e.message||'背景匯出程式載入失敗。'))};worker.postMessage({type,blob:sourceBlob,state,width:canvas.width,height:canvas.height,format:$('format').value.includes('mp4')?'mp4':'webm'})})}
const previousCancelExport=cancelExport;cancelExport=function(...args){previousCancelExport(...args);if(activeExportWorker){activeExportWorker.terminate();activeExportWorker=null;workerReject?.(Error('已取消匯出，編輯仍保留。'));workerReject=null}};
$('cancelExport').onclick=()=>cancelExport();
async function inspectExport(){const state=snapshot(),check=teaching.checkProject(state);if(!check.errors.length){try{const {audio}=await mediaWorker('inspect',state);if(!audio.present)check.warnings.push('來源影片沒有音軌。');else if(audio.sampled&&audio.peak<.0001)check.warnings.push('抽查片段未偵測到聲音，請確認收音。');else check.warnings.push('已檢查部分片段的聲音；仍請試聽完整成片。')}catch(e){check.warnings.push('音訊檢查未完成：'+e.message)}}$('exportChecks').textContent=[...check.errors.map(s=>'需修正：'+s),...check.warnings.map(s=>'提醒：'+s),check.errors.length?'請修正後再匯出。':'片段與字幕範圍檢查通過。'].join('\n');return check}
$('checkExport').onclick=async()=>{if(!allowEdit())return;window.studioBusy=true;exportCancel=false;$('checkExport').disabled=true;$('cancelExport').hidden=false;try{await inspectExport()}finally{window.studioBusy=false;$('checkExport').disabled=false;$('cancelExport').hidden=true;historyButtons()}};
$('exportBtn').onclick=async()=>{
 if(!allowEdit())return;const state=snapshot(),check=teaching.checkProject(state);$('exportChecks').textContent=[...check.errors,...check.warnings].join('\n');if(check.errors.length)return notify(check.errors.join(' '));
 if($('exportEngine').value==='realtime')return realtimeExport();
 if(!window.VideoEncoder||!window.Worker||!window.OffscreenCanvas)return notify('此瀏覽器不支援背景匯出，請選擇相容模式。');
 stopPreview();exporting=true;exportCancel=false;window.backgroundExport=true;document.body.classList.add('busy');$('cancelExport').hidden=false;$('progress').hidden=false;$('progress').value=0;$('downloadLink').hidden=true;$('stateLabel').textContent='背景匯出中';$('exportStatus').textContent='正在讀取影片並檢查音訊…';
 try{const result=await mediaWorker('export',state);if(exportCancel)return;const blob=new Blob([result.buffer],{type:result.mime});if(exportUrl)URL.revokeObjectURL(exportUrl);exportUrl=URL.createObjectURL(blob);$('downloadLink').href=exportUrl;$('downloadLink').download=state.name+(result.mime.includes('mp4')?'.mp4':'.webm');$('downloadLink').hidden=false;$('progress').value=100;$('exportStatus').textContent=`背景匯出完成 · ${(blob.size/1048576).toFixed(2)} MB · 請下載保存`;if(!result.audio.present)$('exportChecks').textContent+='\n提醒：來源沒有音軌，成片為無聲影片。';else if(result.audio.sampled&&result.audio.peak<.0001)$('exportChecks').textContent+='\n提醒：抽查片段未偵測到聲音，請試聽成片。';notify('影片已完成背景匯出。')}
 catch(e){$('exportStatus').textContent=exportCancel?'已取消匯出，編輯仍保留。':'匯出未完成：'+e.message;notify($('exportStatus').textContent)}
 finally{activeExportWorker?.terminate();activeExportWorker=null;workerReject=null;exporting=false;window.backgroundExport=false;document.body.classList.remove('busy');$('cancelExport').hidden=true;$('stateLabel').textContent='可開始編輯';historyButtons()}
};
