(function(root){root.ClassCastRenderer=function(canvas,state){const ctx=canvas.getContext('2d');const $=id=>({value:state.settings[id]});const numberSetting=(id,min,max)=>Math.min(max,Math.max(min,Number(state.settings[id])||0));
function linesFor(text,maxWidth,size){ctx.font=`600 ${size}px "Noto Sans TC", sans-serif`;const lines=[];let line='';for(const char of text){if(char==='\n'||ctx.measureText(line+char).width>maxWidth){lines.push(line);line=char==='\n'?'':char}else line+=char}if(line)lines.push(line);return lines}
function textBox(text,position,color){const w=canvas.width,h=canvas.height,isSubtitle=position==='bottom',size=Math.max(12,w/1280*(isSubtitle?numberSetting('subSize',18,64):42));const lines=linesFor(text,w*.84,size),lh=size*1.5,bh=lines.length*lh+size*.8;const where=isSubtitle?$('subPosition').value:'top';const y=where==='top'?h*.055:where==='center'?(h-bh)/2:h*.94-bh;ctx.save();ctx.globalAlpha=isSubtitle?numberSetting('subOpacity',0,100)/100:.76;ctx.fillStyle=isSubtitle?$('subBg').value:'#0c121e';ctx.fillRect(w*.06,y,w*.88,bh);ctx.globalAlpha=1;ctx.fillStyle=isSubtitle?$('subColor').value:color;ctx.textAlign='center';ctx.textBaseline='top';ctx.shadowColor='#0008';ctx.shadowBlur=2;lines.forEach((line,i)=>ctx.fillText(line,w/2,y+size*.4+i*lh));ctx.restore()};

function paintCursor(x,y,shape,color,size,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=Math.max(2,size*.09);ctx.beginPath();if(shape==='dot'){ctx.arc(x,y,size*.25,0,Math.PI*2);ctx.fill()}else if(shape==='cross'){ctx.moveTo(x-size/2,y);ctx.lineTo(x+size/2,y);ctx.moveTo(x,y-size/2);ctx.lineTo(x,y+size/2);ctx.stroke()}else if(shape==='arrow'){ctx.moveTo(x,y);ctx.lineTo(x+size*.2,y+size);ctx.lineTo(x+size*.42,y+size*.66);ctx.lineTo(x+size*.78,y+size*.7);ctx.closePath();ctx.fill();ctx.strokeStyle='white';ctx.lineWidth=1;ctx.stroke()}else{ctx.arc(x,y,size*.45,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=alpha*.16;ctx.fill()}ctx.restore()}
function paintMark(m,t){if(t<m.start||t>m.end)return;let points=m.points;if(!points?.length)return;const w=canvas.width,h=canvas.height;
  if(m.tool==='cursor'){const elapsed=t-m.start;let p=points[0];for(const q of points){if(q.t>elapsed)break;p=q}paintCursor(p.x*w,p.y*h,m.shape,m.color,m.width*w/1280);for(const q of points){const age=elapsed-q.t;if(q.click&&age>=0&&age<.65){ctx.save();ctx.globalAlpha=1-age/.65;ctx.strokeStyle=m.color;ctx.lineWidth=3*w/1280;ctx.beginPath();ctx.arc(q.x*w,q.y*h,(m.width/2+age*65)*w/1280,0,Math.PI*2);ctx.stroke();ctx.restore()}}return}
  if(m.animated)points=points.filter(p=>p.t<=t-m.start);if(!points.length)return;const a=points[0],b=points[points.length-1],x=a.x*w,y=a.y*h,xx=b.x*w,yy=b.y*h;ctx.save();ctx.strokeStyle=m.color;ctx.lineWidth=m.width*w/1280;ctx.lineCap='round';ctx.lineJoin='round';if(m.tool==='marker'){ctx.globalAlpha=.35;ctx.lineWidth*=4}ctx.beginPath();if(m.tool==='rect')ctx.rect(Math.min(x,xx),Math.min(y,yy),Math.abs(xx-x),Math.abs(yy-y));else if(m.tool==='ellipse')ctx.ellipse((x+xx)/2,(y+yy)/2,Math.max(1,Math.abs(xx-x)/2),Math.max(1,Math.abs(yy-y)/2),0,0,Math.PI*2);else if(m.tool==='arrow'){ctx.moveTo(x,y);ctx.lineTo(xx,yy);const angle=Math.atan2(yy-y,xx-x),len=Math.max(16,ctx.lineWidth*4);ctx.moveTo(xx-len*Math.cos(angle-.5),yy-len*Math.sin(angle-.5));ctx.lineTo(xx,yy);ctx.lineTo(xx-len*Math.cos(angle+.5),yy-len*Math.sin(angle+.5))}else{ctx.moveTo(x,y);for(const p of points)ctx.lineTo(p.x*w,p.y*h);if(points.length===1){ctx.lineTo(x+.1,y+.1)}}ctx.stroke();ctx.restore();}

function privacy(m,t){if(t<m.start||t>=m.end||m.points.length<2)return;const a=m.points[0],b=m.points.at(-1),x=Math.floor(Math.min(a.x,b.x)*canvas.width),y=Math.floor(Math.min(a.y,b.y)*canvas.height),w=Math.ceil(Math.abs(b.x-a.x)*canvas.width),h=Math.ceil(Math.abs(b.y-a.y)*canvas.height);if(!w||!h)return;if(m.privacyMode!=='pixelate'){ctx.fillStyle='#101827';ctx.fillRect(x,y,w,h);return}const block=Math.max(8,Number(m.pixelSize)||24)*canvas.width/1280;const tiny=typeof OffscreenCanvas!=='undefined'?new OffscreenCanvas(Math.max(1,Math.ceil(w/block)),Math.max(1,Math.ceil(h/block))):document.createElement('canvas');tiny.width=Math.max(1,Math.ceil(w/block));tiny.height=Math.max(1,Math.ceil(h/block));tiny.getContext('2d').drawImage(canvas,x,y,w,h,0,0,tiny.width,tiny.height);ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(tiny,0,0,tiny.width,tiny.height,x,y,w,h);ctx.restore()}
return {privacy,paintMark,render(image,t){ctx.fillStyle='#151c2e';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);for(const m of state.marks)if(m.tool==='mosaic')privacy(m,t);const title=String(state.settings.titleText||'').trim();if(title&&t<Number(state.settings.titleDuration))textBox(title,'top',state.settings.titleColor);const active=state.subs.filter(s=>t>=s.start&&t<s.end);if(active.length)textBox(active.map(s=>s.text).join('\n'),'bottom','#ffffff');for(const m of state.marks)if(m.tool!=='mosaic')paintMark(m,t)}}};})(globalThis);
