'use strict';
const C=ClassCastCore;
let previewEpoch=0;
function stopPreview(){previewEpoch++;previewSequence=false;sequenceSeeking=false;window.singlePreviewEnd=null;video.pause()}
let sourceBlob=null,projectId=null,mediaId=null,mediaSaved=false,revision=0,savedRevision=-1,restoring=false,saveTimer,saveQueue=Promise.resolve(),selectedClip=0,marks=[],liveMarks=[],pendingMark=null,cursorPoint=null,cursorTrail=null,previewSequence=false,previewIndex=0,editSubIndex=null;
let processedAudioNode=null,audioGain=null,voiceHighpass=null,audioLimiter=null;
const settingIds=['titleText','titleDuration','titleColor','subSize','subColor','subBg','subOpacity','subPosition','volume','fadeIn','fadeOut','voiceFilter','cursorShape','cursorColor','cursorSize','cursorEnabled','clickEffect','siteCursor','penColor','penWidth','markDuration'];
const settingDefaults=Object.fromEntries(settingIds.map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value]));
const numberSetting=(id,min,max)=>C.clamp($(id).value,min,max);
function readSettings(){return Object.fromEntries(settingIds.map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value]))}
function applySettings(settings){for(const id of settingIds){const el=$(id),value=settings[id]??settingDefaults[id];if(el.type==='checkbox')el.checked=value===true;else el.value=String(value)}updateSettings()}
function snapshot(){return {version:2,name:$('exportName').value.trim()||'教學影片',duration,clips:structuredClone(clips),subs:structuredClone(subs),marks:structuredClone(marks),settings:readSettings()}}
function dirty(){if(restoring||!loaded||!sourceBlob)return;revision++;$('downloadLink').hidden=true;window.unsavedProject=true;$('saveStatus').textContent='尚未儲存…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveProject(false),900)}
function dbOpen(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('此瀏覽器無法使用本機儲存，請下載專案備份。'));const req=indexedDB.open('classcast-studio',2);req.onupgradeneeded=()=>{const db=req.result;for(const name of ['projects','media'])if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('請關閉其他課映分頁後重試。'))})}
const dbPromise=dbOpen();dbPromise.catch(()=>{});
async function dbRead(store,id){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction(store),r=id===undefined?tx.objectStore(store).getAll():tx.objectStore(store).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveProject(announce=true){if(!loaded||!sourceBlob){if(announce)notify('請先錄影或匯入影片。');return false}clearTimeout(saveTimer);const state=snapshot(),id=projectId,mid=mediaId,blob=sourceBlob,rev=revision,includeMedia=!mediaSaved;
  const operation=async()=>{try{const db=await dbPromise;await new Promise((resolve,reject)=>{const tx=db.transaction(['projects','media'],'readwrite');const mediaStore=tx.objectStore('media');if(includeMedia)mediaStore.put({id:mid,blob});else{const existing=mediaStore.get(mid);existing.onsuccess=()=>{if(!existing.result)mediaStore.put({id:mid,blob})}}tx.objectStore('projects').put({id,mediaId:mid,state,updated:Date.now()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('儲存取消'))});if(projectId===id){mediaSaved=true;savedRevision=rev;if(revision===rev){window.unsavedProject=false;$('saveStatus').textContent='已儲存於此瀏覽器'}try{localStorage.setItem('classcast-last-project',id)}catch{}}if(announce)notify('專案已儲存，重新開啟可接續編輯。');return true}catch(e){if(projectId===id){window.unsavedProject=true;$('saveStatus').textContent='未能儲存，請下載備份'}if(announce||revision===rev)notify(e.name==='QuotaExceededError'?'儲存空間不足，請下載專案備份或刪除舊專案。':'本機儲存失敗：'+e.message);return false}};
  saveQueue=saveQueue.then(operation,operation);return saveQueue;
}
const originalLoadVideo=loadVideo;
loadVideo=async function(blob,name,knownDuration){if(busy())return false;window.projectBusy=true;try{if(window.unsavedProject&&loaded){const ok=await saveProject(false);if(!ok&&!confirm('目前專案無法儲存。仍要開啟另一部影片？未備份的編輯將遺失。'))return false}stopPreview();pendingMark=null;cursorTrail=null;if(!await originalLoadVideo(blob,name,knownDuration))return false;sourceBlob=blob;projectId=crypto.randomUUID();mediaId=crypto.randomUUID();mediaSaved=false;revision=0;savedRevision=-1;marks=[];liveMarks=[];selectedClip=0;editSubIndex=null;$('addSub').textContent='加入字幕';applySettings(settingDefaults);$('asrReview').hidden=true;$('downloadLink').hidden=true;$('progress').hidden=true;$('exportStatus').textContent='編輯完成後，請重新匯出影片。';renderLists();dirty();return true}finally{window.projectBusy=false}};
$('saveBtn').onclick=()=>saveProject();
$('projectsBtn').onclick=async()=>{$('projects').showModal();await showProjects()};$('closeProjects').onclick=()=>$('projects').close();
async function showProjects(){try{const projects=(await dbRead('projects')).sort((a,b)=>b.updated-a.updated);$('projectList').replaceChildren();if(!projects.length)$('projectList').textContent='還沒有專案。錄影或匯入影片後會自動儲存。';for(const p of projects){const row=document.createElement('div');row.className='item';const text=document.createElement('span');text.className='text';text.textContent=`${p.state.name} · ${clock(p.state.duration)} · ${new Date(p.updated).toLocaleString('zh-TW')}`;const open=document.createElement('button');open.textContent='開啟';open.onclick=()=>restoreProject(p.id);const remove=document.createElement('button');remove.textContent='刪除';remove.onclick=async()=>{if(busy())return notify('請先完成目前作業。');if(!confirm(`刪除本機專案「${p.state.name}」？此動作無法復原，請先下載需要的備份。`))return;try{if(projectId===p.id)clearTimeout(saveTimer);await saveQueue;const db=await dbPromise;await new Promise((resolve,reject)=>{const tx=db.transaction(['projects','media'],'readwrite'),store=tx.objectStore('projects');store.delete(p.id);const all=store.getAll();all.onsuccess=()=>{if(!all.result.some(x=>x.mediaId===p.mediaId))tx.objectStore('media').delete(p.mediaId)};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});if(projectId===p.id){clearTimeout(saveTimer);projectId=crypto.randomUUID();mediaId=crypto.randomUUID();mediaSaved=false;window.unsavedProject=true;$('saveStatus').textContent='專案已刪除，目前編輯未儲存'}if(localStorage.getItem('classcast-last-project')===p.id)localStorage.removeItem('classcast-last-project');await showProjects()}catch(e){notify(e.message)}};row.append(text,open,remove);$('projectList').append(row)}if(navigator.storage?.estimate){const s=await navigator.storage.estimate();$('storageInfo').textContent=`此網站已使用約 ${(s.usage/1048576).toFixed(1)} MB，可用上限約 ${(s.quota/1073741824).toFixed(1)} GB。重要專案請另下載備份。`}}catch(e){$('projectList').textContent='無法讀取專案：'+e.message}}
async function restoreProject(id){if(busy())return notify('請先完成目前作業。');window.projectBusy=true;try{if(loaded&&window.unsavedProject&&!await saveProject(false))throw Error('請先備份目前專案，再開啟其他專案。');const p=await dbRead('projects',id);if(!p)throw Error('專案已不存在。');const media=await dbRead('media',p.mediaId);if(!media?.blob)throw Error('找不到原始影片，請匯入專案備份。');const state=C.normalize(p.state,p.state.duration);restoring=true;window.projectBusy=false;if(!await loadVideo(media.blob,state.name,state.duration))throw Error('影片無法載入。');clearTimeout(saveTimer);const actual=C.normalize(state,duration);projectId=p.id;mediaId=p.mediaId;mediaSaved=true;clips=actual.clips;subs=actual.subs;marks=actual.marks;applySettings(actual.settings);$('exportName').value=actual.name;$('projectName').textContent=actual.name;renderLists();revision=0;savedRevision=0;window.unsavedProject=false;$('saveStatus').textContent='已恢復本機專案';localStorage.setItem('classcast-last-project',id);$('projects').close();notify('專案已恢復，影片、字幕與設定均已載入。')}catch(e){notify('無法恢復專案：'+e.message)}finally{restoring=false;window.projectBusy=false}}
$('saveCopy').onclick=async()=>{if(!allowEdit())return;projectId=crypto.randomUUID();revision++;$('downloadLink').hidden=true;window.unsavedProject=true;await saveProject();await showProjects()};
const backupMagic=new TextEncoder().encode('CCAST02\n');
function packProject(state,blob){const json=new TextEncoder().encode(JSON.stringify(state)),length=new Uint8Array(4);new DataView(length.buffer).setUint32(0,json.length,true);return new Blob([backupMagic,length,json,blob],{type:'application/octet-stream'})}
$('backupProject').onclick=()=>{if(!allowEdit())return;download(packProject(snapshot(),sourceBlob),($('exportName').value||'教學影片')+'.classcast');notify('專案備份已開始下載，包含原始影片與編輯資料。')};
$('importProject').onclick=()=>{if(!busy())$('projectFile').click()};
$('projectFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(busy())return;window.projectBusy=true;try{const prefix=new Uint8Array(await f.slice(0,12).arrayBuffer());if(prefix.length<12||new TextDecoder().decode(prefix.slice(0,8))!=='CCAST02\n')throw Error('不是有效的 .classcast 備份。');const length=new DataView(prefix.buffer).getUint32(8,true);if(length>32*1024*1024||length+12>=f.size)throw Error('備份資料長度無效。');const state=JSON.parse(await f.slice(12,12+length).text());C.normalize(state,state.duration);window.projectBusy=false;if(!await loadVideo(f.slice(12+length),state.name,state.duration))return;const valid=C.normalize(state,duration);restoring=true;clips=valid.clips;subs=valid.subs;marks=valid.marks;applySettings(valid.settings);renderLists();restoring=false;dirty();await saveProject();$('projects').close()}catch(e){notify('匯入失敗：'+e.message)}finally{restoring=false;window.projectBusy=false;e.target.value=''}};

// Timeline: clip order is the exported order; handles map to the original source.
const baseRenderLists=renderLists;
renderLists=function(){stopPreview();editSubIndex=null;$('addSub').textContent='加入字幕';baseRenderLists();selectedClip=Math.min(Math.max(0,selectedClip),Math.max(0,clips.length-1));const nodes=[...$('clipTrack').children];nodes.forEach((node,i)=>{node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label',`選擇片段 ${i+1}，拖曳可排序`);node.classList.toggle('chosen',selectedClip===i);node.draggable=true;node.onclick=()=>selectClip(i);node.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectClip(i)}};node.ondragstart=e=>e.dataTransfer.setData('text/plain',String(i));node.ondragover=e=>e.preventDefault();node.ondrop=e=>{e.preventDefault();if(!allowEdit())return;const from=Number(e.dataTransfer.getData('text/plain'));if(!Number.isInteger(from)||from<0||from>=clips.length)return;const [moved]=clips.splice(from,1);clips.splice(i,0,moved);selectedClip=i;renderLists()}});[...$('clipList').children].forEach((row,i)=>{const buttons=row.querySelectorAll('button');buttons[0].onclick=async()=>{if(!allowEdit())return;stopPreview();const epoch=previewEpoch;selectedClip=i;previewIndex=i;try{await ensureAudio();if(epoch!==previewEpoch)return;await seekTo(clips[i].start);if(epoch!==previewEpoch)return;await video.play();window.singlePreviewEnd=clips[i].end}catch(e){notify(e.message)}};const edit=document.createElement('button');edit.textContent='選取';edit.onclick=()=>selectClip(i);row.append(edit)});[...$('subtitleList').children].forEach((row,i)=>{row.querySelector('button').onclick=()=>{if(!allowEdit())return;editSubIndex=i;const s=subs[i];$('subStart').value=s.start;$('subEnd').value=s.end;$('subText').value=s.text;$('addSub').textContent='儲存字幕';$('subText').focus()}});updateTimeline();renderMarkList();dirty()};
function selectClip(index){if(!allowEdit())return;stopPreview();selectedClip=index;$('trimStart').value=clips[index].start.toFixed(2);$('trimEnd').value=clips[index].end.toFixed(2);video.currentTime=clips[index].start;updateTimeline();[...$('clipTrack').children].forEach((el,i)=>el.classList.toggle('chosen',i===index))}
function updateTimeline(){const c=clips[selectedClip];$('sourceTimeline').classList.toggle('ready',!!c);$('rangeSelection').hidden=!c;if(!c)return;const start=c.start/duration*100,end=c.end/duration*100;$('rangeSelection').style.left=start+'%';$('rangeSelection').style.width=(end-start)+'%';$('timelineLabel').textContent=`片段 ${selectedClip+1}　${c.start.toFixed(2)} – ${c.end.toFixed(2)} 秒`;$('leftHandle').setAttribute('aria-valuemax',String(duration));$('rightHandle').setAttribute('aria-valuemax',String(duration));$('leftHandle').setAttribute('aria-valuenow',String(c.start));$('rightHandle').setAttribute('aria-valuenow',String(c.end));}
function handleTime(e){const b=$('sourceTimeline').getBoundingClientRect();return C.clamp((e.clientX-b.left)/b.width*duration,0,duration)}
for(const [id,side] of [['leftHandle','start'],['rightHandle','end']]){let dragging=false;$(id).onpointerdown=e=>{if(!allowEdit())return;e.preventDefault();e.stopPropagation();stopPreview();dragging=true;$(id).setPointerCapture(e.pointerId)};$(id).onpointermove=e=>{if(!dragging)return;const c=clips[selectedClip],t=handleTime(e);c[side]=side==='start'?C.clamp(t,0,c.end-.1):C.clamp(t,c.start+.1,duration);video.currentTime=c[side];updateTimeline()};const end=()=>{if(dragging){dragging=false;renderLists()}};$(id).onpointerup=end;$(id).onpointercancel=end;$(id).onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key)||!allowEdit())return;e.preventDefault();const c=clips[selectedClip],t=c[side]+(e.key==='ArrowRight'?1:-1)*(e.shiftKey?1:.1);c[side]=side==='start'?C.clamp(t,0,c.end-.1):C.clamp(t,c.start+.1,duration);renderLists()}}
$('sourceTimeline').onclick=e=>{if(e.target.closest('.range-handle')||!loaded||busy())return;stopPreview();video.currentTime=handleTime(e)};
$('splitClip').onclick=()=>{if(!allowEdit())return;try{clips=C.split(clips,selectedClip,video.currentTime);renderLists()}catch(e){notify(e.message)}};
$('previewEdit').onclick=async()=>{if(!allowEdit()||!clips.length)return;if(previewSequence){stopPreview();return}stopPreview();const epoch=previewEpoch;try{await ensureAudio();if(epoch!==previewEpoch)return;previewSequence=true;previewIndex=0;await seekTo(clips[0].start);if(epoch===previewEpoch&&previewSequence)await video.play()}catch(e){stopPreview();notify(e.message)}};
$('addSub').onclick=()=>{if(!allowEdit())return;const start=Number($('subStart').value),end=Number($('subEnd').value),text=$('subText').value.trim();if(!validRange(start,end)||!text)return notify('請填寫字幕內容與有效時間範圍。');if(editSubIndex!==null&&subs[editSubIndex])subs[editSubIndex]={start,end:Math.min(duration,end),text};else subs.push({start,end:Math.min(duration,end),text});editSubIndex=null;$('addSub').textContent='加入字幕';$('subText').value='';renderLists()};

// Same Web Audio graph feeds preview and the exported MediaStream.
function setupAudioNodes(){voiceHighpass=exportAudioContext.createBiquadFilter();voiceHighpass.type='highpass';voiceHighpass.frequency.value=0;audioGain=exportAudioContext.createGain();audioLimiter=exportAudioContext.createDynamicsCompressor();audioLimiter.threshold.value=-2;audioLimiter.knee.value=0;audioLimiter.ratio.value=20;exportAudioSource.connect(voiceHighpass);voiceHighpass.connect(audioGain);audioGain.connect(audioLimiter);audioLimiter.connect(exportAudioContext.destination);processedAudioNode=audioLimiter}
async function ensureAudio(){if(!exportAudioContext){exportAudioContext=new AudioContext();exportAudioSource=exportAudioContext.createMediaElementSource(video);setupAudioNodes()}await exportAudioContext.resume();updateAudioGain()}
function updateAudioGain(){if(!audioGain||!loaded)return;const index=exporting?(window.exportClipIndex??0):previewSequence?previewIndex:Math.max(0,clips.findIndex(c=>video.currentTime>=c.start&&video.currentTime<=c.end));const time=C.outputTime(clips,index,video.currentTime),total=totalDuration();const gain=C.gainAt(time,total,numberSetting('volume',0,200)/100,numberSetting('fadeIn',0,30),numberSetting('fadeOut',0,30));audioGain.gain.setTargetAtTime(gain,exportAudioContext.currentTime,.008);voiceHighpass.frequency.setTargetAtTime($('voiceFilter').checked?100:0,exportAudioContext.currentTime,.01)}
function updateSettings(){$('subSizeValue').textContent=$('subSize').value;$('volumeValue').textContent=$('volume').value+'%';updateAudioGain();applyCursor();if(loaded)draw()}
for(const id of settingIds)$(id).addEventListener('input',()=>{updateSettings();dirty()});$('exportName').addEventListener('input',()=>{$('projectName').textContent=$('exportName').value;dirty()});
textBox=function(text,position,color){const w=canvas.width,h=canvas.height,isSubtitle=position==='bottom',size=Math.max(12,w/1280*(isSubtitle?numberSetting('subSize',18,64):42));const lines=linesFor(text,w*.84,size),lh=size*1.5,bh=lines.length*lh+size*.8;const where=isSubtitle?$('subPosition').value:'top';const y=where==='top'?h*.055:where==='center'?(h-bh)/2:h*.94-bh;ctx.save();ctx.globalAlpha=isSubtitle?numberSetting('subOpacity',0,100)/100:.76;ctx.fillStyle=isSubtitle?$('subBg').value:'#0c121e';ctx.fillRect(w*.06,y,w*.88,bh);ctx.globalAlpha=1;ctx.fillStyle=isSubtitle?$('subColor').value:color;ctx.textAlign='center';ctx.textBaseline='top';ctx.shadowColor='#0008';ctx.shadowBlur=2;lines.forEach((line,i)=>ctx.fillText(line,w/2,y+size*.4+i*lh));ctx.restore()};
const baseDraw=draw;draw=function(){baseDraw();if(loaded)renderAnnotations(false)};

// Non-destructive annotations use normalized source-video coordinates.
function beginLiveAnnotations(){liveMarks=[];pendingMark=null;cursorTrail=null;cursorPoint=null}
function finishLiveAnnotations(length){const all=[...liveMarks];if(pendingMark)all.push(pendingMark);if(cursorTrail)all.push(cursorTrail);return structuredClone(all).map(m=>({...m,start:C.clamp(m.start,0,length),end:C.clamp(m.end,0,length)})).filter(m=>m.end>m.start)}
function restoreLiveAnnotations(recorded){marks=recorded.map(m=>({...m,end:Math.min(m.end,duration)})).filter(m=>m.end>m.start);renderMarkList();dirty()}
function markTime(live){return live?Math.max(0,((pausedAt||Date.now())-recordStart-pauseTotal)/1000):video.currentTime}
function paintCursor(x,y,shape,color,size,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=Math.max(2,size*.09);ctx.beginPath();if(shape==='dot'){ctx.arc(x,y,size*.25,0,Math.PI*2);ctx.fill()}else if(shape==='cross'){ctx.moveTo(x-size/2,y);ctx.lineTo(x+size/2,y);ctx.moveTo(x,y-size/2);ctx.lineTo(x,y+size/2);ctx.stroke()}else if(shape==='arrow'){ctx.moveTo(x,y);ctx.lineTo(x+size*.2,y+size);ctx.lineTo(x+size*.42,y+size*.66);ctx.lineTo(x+size*.78,y+size*.7);ctx.closePath();ctx.fill();ctx.strokeStyle='white';ctx.lineWidth=1;ctx.stroke()}else{ctx.arc(x,y,size*.45,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=alpha*.16;ctx.fill()}ctx.restore()}
function paintMark(m,t){if(t<m.start||t>m.end)return;let points=m.points;if(!points?.length)return;const w=canvas.width,h=canvas.height;
  if(m.tool==='cursor'){const elapsed=t-m.start;let p=points[0];for(const q of points){if(q.t>elapsed)break;p=q}paintCursor(p.x*w,p.y*h,m.shape,m.color,m.width*w/1280);for(const q of points){const age=elapsed-q.t;if(q.click&&age>=0&&age<.65){ctx.save();ctx.globalAlpha=1-age/.65;ctx.strokeStyle=m.color;ctx.lineWidth=3*w/1280;ctx.beginPath();ctx.arc(q.x*w,q.y*h,(m.width/2+age*65)*w/1280,0,Math.PI*2);ctx.stroke();ctx.restore()}}return}
  if(m.animated)points=points.filter(p=>p.t<=t-m.start);if(!points.length)return;const a=points[0],b=points[points.length-1],x=a.x*w,y=a.y*h,xx=b.x*w,yy=b.y*h;ctx.save();ctx.strokeStyle=m.color;ctx.lineWidth=m.width*w/1280;ctx.lineCap='round';ctx.lineJoin='round';if(m.tool==='marker'){ctx.globalAlpha=.35;ctx.lineWidth*=4}ctx.beginPath();if(m.tool==='rect')ctx.rect(Math.min(x,xx),Math.min(y,yy),Math.abs(xx-x),Math.abs(yy-y));else if(m.tool==='ellipse')ctx.ellipse((x+xx)/2,(y+yy)/2,Math.max(1,Math.abs(xx-x)/2),Math.max(1,Math.abs(yy-y)/2),0,0,Math.PI*2);else if(m.tool==='arrow'){ctx.moveTo(x,y);ctx.lineTo(xx,yy);const angle=Math.atan2(yy-y,xx-x),len=Math.max(16,ctx.lineWidth*4);ctx.moveTo(xx-len*Math.cos(angle-.5),yy-len*Math.sin(angle-.5));ctx.lineTo(xx,yy);ctx.lineTo(xx-len*Math.cos(angle+.5),yy-len*Math.sin(angle+.5))}else{ctx.moveTo(x,y);for(const p of points)ctx.lineTo(p.x*w,p.y*h);if(points.length===1){ctx.lineTo(x+.1,y+.1)}}ctx.stroke();ctx.restore();}
function renderAnnotations(live){const time=markTime(live);for(const m of (live?liveMarks:marks))paintMark(m,time);if(pendingMark)paintMark(pendingMark,time);if(cursorTrail)paintMark(cursorTrail,time);if(!exporting&&cursorPoint&&$('cursorEnabled').checked)paintCursor(cursorPoint.x*canvas.width,cursorPoint.y*canvas.height,$('cursorShape').value,$('cursorColor').value,numberSetting('cursorSize',12,72)*canvas.width/1280)}
function pointOf(e){const b=canvas.getBoundingClientRect();return{x:C.clamp((e.clientX-b.left)/b.width,0,1),y:C.clamp((e.clientY-b.top)/b.height,0,1)}}
function canAnnotate(){return !exporting&&!recordPreparing&&!window.projectBusy&&!loading&&!window.studioBusy&&(loaded||recorder)&&recorder?.state!=='paused'}
function recordCursor(point,click=false){const live=!!recorder;if(!$('cursorEnabled').checked||(!live&&video.paused))return;const t=markTime(live);if(!cursorTrail){cursorTrail={tool:'cursor',start:t,end:t+.1,points:[],color:$('cursorColor').value,width:numberSetting('cursorSize',12,72),shape:$('cursorShape').value}}const last=cursorTrail.points.at(-1);if(!click&&last&&t-cursorTrail.start-last.t<.03)return;cursorTrail.points.push({...point,t:t-cursorTrail.start,click:click&&$('clickEffect').checked});cursorTrail.end=live?t+.15:Math.min(duration,t+.15)}
function finishCursor(){if(cursorTrail){(recorder?liveMarks:marks).push(cursorTrail);cursorTrail=null;if(!recorder){renderMarkList();dirty()}}}
canvas.addEventListener('pointermove',e=>{if(!canAnnotate())return;const point=pointOf(e);cursorPoint=point;recordCursor(point);if(pendingMark){const t=markTime(!!recorder)-pendingMark.start;pendingMark.points.push({...point,t});pendingMark.end=recorder?markTime(true)+numberSetting('markDuration',.2,3600):Math.min(duration,Math.max(pendingMark.end,video.currentTime+numberSetting('markDuration',.2,3600)))}if(!recorder)draw()});
canvas.addEventListener('pointerdown',e=>{if(!canAnnotate())return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const p=pointOf(e),live=!!recorder,t=markTime(live);cursorPoint=p;recordCursor(p,true);if($('drawTool').value==='none')return;pendingMark={tool:$('drawTool').value,start:t,end:live?t+numberSetting('markDuration',.2,3600):Math.min(duration,t+numberSetting('markDuration',.2,3600)),color:$('penColor').value,width:numberSetting('penWidth',2,20),points:[{...p,t:0}],animated:live||!video.paused}});
function finishMark(){if(pendingMark){if(pendingMark.end>pendingMark.start)(recorder?liveMarks:marks).push(pendingMark);pendingMark=null;if(!recorder){renderMarkList();dirty()}}}
canvas.addEventListener('pointerup',finishMark);canvas.addEventListener('pointercancel',finishMark);canvas.addEventListener('pointerleave',()=>{cursorPoint=null;finishCursor();if(!recorder)draw()});video.addEventListener('pause',finishCursor);
$('undoMark').onclick=()=>{if(!canAnnotate())return;(recorder?liveMarks:marks).pop();renderMarkList();dirty();draw()};$('clearMarks').onclick=()=>{if(!canAnnotate())return;if(recorder)liveMarks=[];else marks=[];pendingMark=null;cursorTrail=null;cursorPoint=null;renderMarkList();dirty();draw()};
function renderMarkList(){$('annotationList').replaceChildren();const names={pen:'畫筆',marker:'螢光筆',ellipse:'橢圓',rect:'方框',arrow:'箭頭',cursor:'滑鼠軌跡'};marks.forEach((m,i)=>{const row=document.createElement('div');row.className='item';const text=document.createElement('span');text.className='text';text.textContent=`${names[m.tool]} · ${m.start.toFixed(1)} – ${m.end.toFixed(1)} 秒`;row.append(text,makeButton('跳到位置',()=>{video.currentTime=m.start}),makeButton('刪除',()=>{marks.splice(i,1);renderMarkList();dirty()}));$('annotationList').append(row)})}
function applyCursor(){const color=$('cursorColor').value,size=Math.min(64,numberSetting('cursorSize',12,72)),shape=$('cursorShape').value;const paths={ring:'<circle cx="32" cy="32" r="22" fill="none" stroke-width="4"/>',dot:'<circle cx="32" cy="32" r="12"/>',cross:'<path d="M8 32H56M32 8V56" fill="none" stroke-width="4"/>',arrow:'<path d="M15 8L22 54L33 36L51 37Z" stroke-width="2"/>'};const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 64 64"><g fill="${color}" stroke="${color}">${paths[shape]||paths.ring}</g></svg>`;const hot=shape==='arrow'?Math.round(size*15/64):Math.round(size/2);document.documentElement.style.setProperty('--custom-cursor',`url("data:image/svg+xml,${encodeURIComponent(svg)}") ${hot} ${shape==='arrow'?Math.round(size*8/64):hot}, auto`);document.body.classList.toggle('custom-cursor',$('siteCursor').checked);canvas.classList.toggle('cursor-overlay',$('cursorEnabled').checked);canvas.style.cursor=$('cursorEnabled').checked?'none':$('drawTool').value==='none'?'default':'crosshair'}
$('drawTool').onchange=applyCursor;

let sequenceSeeking=false;
function studioFrame(){if(loaded){$('timelinePlayhead').style.left=(video.currentTime/duration*100)+'%';updateAudioGain();if(!exporting&&previewSequence&&clips[previewIndex]&&!sequenceSeeking&&(video.currentTime>=clips[previewIndex].end-.02||video.ended)){sequenceSeeking=true;const epoch=previewEpoch;video.pause();previewIndex++;if(previewIndex>=clips.length){previewSequence=false;sequenceSeeking=false}else seekTo(clips[previewIndex].start).then(()=>{if(epoch===previewEpoch&&previewSequence)return video.play()}).catch(e=>{previewSequence=false;notify(e.message)}).finally(()=>{if(epoch===previewEpoch)sequenceSeeking=false})}if(window.singlePreviewEnd&&!exporting&&video.currentTime>=window.singlePreviewEnd){video.pause();window.singlePreviewEnd=null}}$('previewEdit').textContent=previewSequence?'停止成片預覽':'預覽成片';requestAnimationFrame(studioFrame)}requestAnimationFrame(studioFrame);
// Freeze editing inputs during export; cancel remains available.
let exportLocks=[];new MutationObserver(()=>{if(exporting&&!exportLocks.length){exportLocks=[...document.querySelectorAll('button,input,select')].filter(el=>el.id!=='cancelExport').map(el=>[el,el.disabled]);exportLocks.forEach(([el])=>el.disabled=true)}else if(!exporting&&exportLocks.length){exportLocks.forEach(([el,disabled])=>el.disabled=disabled);exportLocks=[];$('exportBtn').disabled=false;$('playBtn').disabled=!loaded;$('seek').disabled=!loaded}}).observe(document.body,{attributes:true,attributeFilter:['class']});
updateSettings();
(async()=>{try{const id=localStorage.getItem('classcast-last-project');if(id){const p=await dbRead('projects',id);if(p&&!loaded&&!loading&&!recorder){$('projects').showModal();await showProjects();notify('找到已儲存的專案，點選「開啟」即可接續。')}}}catch{}})();
document.addEventListener('visibilitychange',()=>{if(document.hidden&&loaded&&window.unsavedProject)saveProject(false)});

// Whisper speech recognition, with a decode path and a real-time audio fallback.
let asrWorker=null,asrToken=0,asrResult=[],extractionCancel=null;
async function extractAudio(token){const audioContext=new AudioContext({sampleRate:16000});try{const decoded=await audioContext.decodeAudioData(await sourceBlob.arrayBuffer());if(token!==asrToken)throw Error('已取消');const out=new Float32Array(decoded.length);for(let c=0;c<decoded.numberOfChannels;c++){const channel=decoded.getChannelData(c);for(let i=0;i<out.length;i++)out[i]+=channel[i]/decoded.numberOfChannels}return out}catch(e){if(token!==asrToken)throw e}finally{await audioContext.close()}
  $('asrStatus').textContent='此格式需即時擷取音訊，請保持頁面開啟；時間約等於影片長度。';
  const ac=new AudioContext({sampleRate:16000}),player=document.createElement('video');player.src=sourceUrl;player.playsInline=true;player.preload='auto';let worklet,source,silence;
  try{await ac.audioWorklet.addModule('audio-capture.js');source=ac.createMediaElementSource(player);worklet=new AudioWorkletNode(ac,'classcast-capture');silence=ac.createGain();silence.gain.value=0;source.connect(worklet);worklet.connect(silence);silence.connect(ac.destination);const chunks=[];let count=0;await ac.resume();
    await new Promise((resolve,reject)=>{let lastProgress=Date.now(),lastTime=-1,done=false;const finish=error=>{if(done)return;done=true;clearInterval(timer);extractionCancel=null;error?reject(error):resolve()};extractionCancel=()=>finish(Error('已取消'));worklet.port.onmessage=({data})=>{if(data==='flushed')finish();else{chunks.push(data);count+=data.length}};player.onended=()=>worklet.port.postMessage('flush');player.onerror=()=>finish(Error('無法擷取此影片音訊。'));const timer=setInterval(()=>{if(token!==asrToken)return finish(Error('已取消'));if(player.currentTime!==lastTime){lastTime=player.currentTime;lastProgress=Date.now()}if(Date.now()-lastProgress>30000)return finish(Error('音訊擷取停滯，請重試。'));$('asrProgress').value=Math.min(100,player.currentTime/duration*100);$('asrStatus').textContent=`擷取音訊 ${clock(player.currentTime)} / ${clock(duration)}`;if(player.currentTime>=duration-.02&&!player.paused){player.pause();worklet.port.postMessage('flush')}},200);player.play().catch(finish)});
    const out=new Float32Array(count);let offset=0;for(const chunk of chunks){out.set(chunk,offset);offset+=chunk.length}return out;
  }finally{extractionCancel=null;player.pause();player.removeAttribute('src');player.load();source?.disconnect();worklet?.disconnect();silence?.disconnect();await ac.close()}
}
function endAsr(){window.studioBusy=false;$('autoSub').disabled=false;$('cancelAsr').hidden=true;$('asrProgress').hidden=true;$('stateLabel').textContent=loaded?'可開始編輯':'準備就緒'}
$('autoSub').onclick=async()=>{if(!allowEdit())return;video.pause();previewSequence=false;const token=++asrToken;window.studioBusy=true;$('autoSub').disabled=true;$('cancelAsr').hidden=false;$('asrProgress').hidden=false;$('asrProgress').removeAttribute('value');$('asrReview').hidden=true;$('stateLabel').textContent='產生自動字幕';$('asrStatus').textContent='正在擷取影片音訊…';try{const pcm=await extractAudio(token);if(token!==asrToken)return;if(!pcm.length)throw Error('影片沒有可辨識的音訊。');let peak=0;for(let i=0;i<pcm.length;i++)peak=Math.max(peak,Math.abs(pcm[i]));if(peak<.0001)throw Error('音訊為靜音，請確認錄影有收音。');if(!asrWorker)asrWorker=new Worker('asr-worker.js',{type:'module'});asrWorker.onerror=e=>{if(token!==asrToken)return;$('asrStatus').textContent='辨識引擎無法載入，請確認網路連線後重試。';asrWorker.terminate();asrWorker=null;endAsr()};asrWorker.onmessage=({data})=>{if(token!==asrToken)return;if(data.type==='download'){$('asrProgress').value=data.progress||0;$('asrStatus').textContent=`下載模型 ${data.file}：${Math.round(data.progress||0)}%`}else if(data.type==='status'){$('asrProgress').removeAttribute('value');$('asrStatus').textContent=data.text}else if(data.type==='error'){$('asrStatus').textContent='辨識未完成：'+data.message+'。可重試或使用手動字幕。';endAsr()}else if(data.type==='result'){asrResult=data.segments.map(s=>({...s,end:Math.min(s.end,duration)})).filter(s=>validRange(s.start,s.end));$('asrProgress').value=100;$('asrStatus').textContent='辨識完成。請預覽並校正內容，再套用到字幕。';$('asrSummary').textContent=`共 ${asrResult.length} 段字幕；校正後也可在字幕清單繼續修改。`;$('asrPreview').replaceChildren();asrResult.forEach((s,i)=>{const row=document.createElement('label');row.textContent=`${clock(s.start)} – ${clock(s.end)}`;const input=document.createElement('textarea');input.value=s.text;input.maxLength=240;input.setAttribute('aria-label',`辨識字幕 ${i+1}`);input.oninput=()=>asrResult[i].text=input.value;row.append(input);$('asrPreview').append(row)});$('asrReview').hidden=false;endAsr()}};asrWorker.postMessage({type:'transcribe',audio:pcm.buffer,model:$('asrModel').value,language:$('asrLanguage').value},[pcm.buffer])}catch(e){if(token!==asrToken)return;$('asrStatus').textContent=e.message;endAsr()}};
$('cancelAsr').onclick=()=>{asrToken++;extractionCancel?.();asrWorker?.terminate();asrWorker=null;$('asrStatus').textContent='已取消辨識，原有字幕未變更。';endAsr()};
function applyAsr(append){if(!allowEdit())return;const valid=asrResult.filter(s=>s.text.trim()).map(s=>({...s,text:s.text.trim()}));if(!valid.length)return notify('沒有可套用的字幕。');subs=append?[...subs,...valid]:valid;editSubIndex=null;$('addSub').textContent='加入字幕';renderLists();$('asrReview').hidden=true;notify('自動字幕已套用。')}
$('applyAsr').onclick=()=>applyAsr(false);$('appendAsr').onclick=()=>applyAsr(true);$('discardAsr').onclick=()=>{asrResult=[];$('asrReview').hidden=true};

$('playBtn').onclick=async()=>{if(!allowEdit())return;const paused=video.paused;stopPreview();if(paused){const epoch=previewEpoch;try{await ensureAudio();if(epoch===previewEpoch)await video.play()}catch(e){notify(e.message)}}};
$('seek').oninput=()=>{if(!busy()){stopPreview();video.currentTime=Number($('seek').value)}};
