const stabilityButton=document.createElement('button');stabilityButton.textContent='驗證暫存、取消與作業互斥';document.body.prepend(stabilityButton);
stabilityButton.onclick=async()=>{results.textContent='STABILITY RUNNING';try{
 const w=frame.contentWindow,d=w.document;if(d.getElementById('projects').open)d.getElementById('projects').close();await w.loadVideo(await fixture(),'可靠性驗證.webm',3.2);await w.refreshCompatibility();assert(d.getElementById('compatibilitySummary').textContent.includes('本機暫存'),'capability probe verifies actual disk writes');
 w.addSubtitle(0,2,'暫存驗證');const state=JSON.stringify(w.snapshot());const exporting=d.getElementById('exportBtn').onclick();assert(w.ClassCastOperations.state==='export-background','export owns the operation');assert(await w.loadVideo(new Blob(['invalid']),'blocked')===false,'import blocked while export owns state');assert(JSON.stringify(w.snapshot())===state,'blocked import preserves state');await exporting;
 assert(!d.getElementById('downloadLink').hidden,'disk export completed');assert(d.getElementById('exportStorageHint').textContent.includes('分段寫入'),'disk output path selected');const dir=await w.ClassCastExportStorage.folder(),names=[];for await(const name of dir.keys())if(name.startsWith('export-'))names.push(name);const live=[];for(const name of names){const file=await(await dir.getFileHandle(name)).getFile();if(file.size)live.push({name,file})}assert(live.length>0,'encoded output is stored in an actual file');const clean=await w.ClassCastExportStorage.clearUnused();assert(clean.skipped>=1,'cache cleanup preserves files owned by open tabs');const output=await fetch(d.getElementById('downloadLink').href).then(r=>r.blob());assert(output.size>1000,'download link remains readable after cleanup');
 d.getElementById('trimStart').value=0;d.getElementById('trimEnd').value=3;for(let i=0;i<8;i++)d.getElementById('addClip').click();const work=d.getElementById('exportBtn').onclick();await pause(300);d.getElementById('cancelExport').click();await work;assert(w.ClassCastOperations.state==='idle','cancel releases operation ownership');assert(!d.getElementById('exportBtn').disabled,'cancel restores controls');const after=[];for await(const name of dir.keys())if(name.startsWith('export-'))after.push(name);assert(after.length<=live.length,'cancel removes incomplete output file');
 d.getElementById('exportEngine').value='realtime';const compatible=d.getElementById('exportBtn').onclick();d.getElementById('cancelExport').click();await compatible;assert(w.ClassCastOperations.state==='idle'&&d.getElementById('cancelExport').hidden,'immediate compatibility cancellation releases lifecycle');
 const beforeAsr=JSON.stringify(w.snapshot().subs),transcribing=d.getElementById('autoSub').onclick();assert(w.ClassCastOperations.state==='transcribing','speech extraction owns operation');d.getElementById('cancelAsr').click();await transcribing;assert(w.ClassCastOperations.state==='idle'&&!d.getElementById('exportBtn').disabled,'cancelled speech extraction releases controls');assert(JSON.stringify(w.snapshot().subs)===beforeAsr,'speech cancellation preserves subtitles');
 results.textContent+='\nALL STABILITY CHECKS PASSED';
}catch(e){results.textContent+='\nFAIL '+e.stack}};
const fallbackButton=document.createElement('button');fallbackButton.textContent='驗證無磁碟環境的安全上限';document.body.prepend(fallbackButton);
fallbackButton.onclick=async()=>{results.textContent='FALLBACK RUNNING';try{const blob=await fixture(),state={duration:3.2,clips:[{start:0,end:2}],subs:[],marks:[],settings:{volume:100,fadeIn:0,fadeOut:0}};const run=state=>new Promise((resolve,reject)=>{const worker=new Worker('/export-worker.js',{type:'module'});worker.onerror=e=>{worker.terminate();reject(Error(e.message))};worker.onmessage=({data})=>{if(['complete','error'].includes(data.type)){worker.terminate();resolve(data)}};worker.postMessage({type:'export',blob,state,width:160,height:90,format:'mp4'})});const short=await run(state);assert(short.storage==='memory'&&short.buffer.byteLength>1000,'small export can fall back to memory');const long=await run({...state,clips:Array.from({length:70},()=>({start:0,end:3}))});assert(long.type==='error'&&long.message.includes('安全範圍'),'large output rejected before memory accumulation');results.textContent+='\nFALLBACK CHECKS PASSED'}catch(e){results.textContent+='\nFAIL '+e.stack}};
const longButton=document.createElement('button');longButton.textContent='驗證45分鐘長成片分段匯出';document.body.prepend(longButton);
longButton.onclick=async()=>{results.textContent='LONG EXPORT PREPARING';const w=frame.contentWindow,name='export-'+crypto.randomUUID()+'.mp4';let worker;try{const blob=await fixture();const M=await import('/vendor/mediabunny-1.61.3.mjs');const state={version:2,duration:3.2,clips:Array.from({length:900},()=>({start:0,end:3})),subs:[],marks:[],settings:{volume:100,fadeIn:0,fadeOut:0}};await w.ClassCastExportStorage.hold(name);worker=new Worker('/export-worker.js',{type:'module'});const started=performance.now();const result=await new Promise((resolve,reject)=>{worker.onmessage=({data})=>{if(data.type==='progress')results.textContent='LONG EXPORT '+Math.round(data.value)+'% · '+Math.round(data.bytes/1024)+' KB';else if(data.type==='error')reject(Error(data.message));else if(data.type==='complete')resolve(data)};worker.onerror=e=>reject(Error(e.message));worker.postMessage({type:'export',blob,state,temporaryName:name,width:160,height:90,format:'mp4'})});assert(result.storage==='disk'&&result.file?.size>1000&&!result.buffer,'45-minute export returns disk file without whole-file ArrayBuffer');const input=new M.Input({source:new M.BlobSource(result.file),formats:M.ALL_FORMATS});const duration=await input.computeDuration();assert(duration>2699.9&&duration<2700.2,'45-minute output has correct duration');const track=await input.getPrimaryVideoTrack(),sink=new M.CanvasSink(track,{poolSize:1});assert(!!await sink.getCanvas(2699),'last minute of long output decodes');input.dispose();results.textContent+='\nLONG EXPORT PASSED in '+Math.round((performance.now()-started)/1000)+' seconds'}catch(e){results.textContent+='\nFAIL '+e.stack}finally{worker?.terminate();await w.ClassCastExportStorage.remove(name).catch(()=>{})}};
