const teachingButton=document.createElement('button');teachingButton.textContent='驗證教學新功能';document.body.prepend(teachingButton);
teachingButton.onclick=async()=>{results.textContent='TEACHING RUNNING';try{
const w=frame.contentWindow,d=w.document;if(d.getElementById('projects').open)d.getElementById('projects').close();const media=await fixture();assert(await w.loadVideo(media,'新功能驗證.webm',3.2),'load fixture');w.addSubtitle(.2,2,'光合做用');d.getElementById('undoEdit').click();assert(w.snapshot().subs.length===0,'undo subtitle addition');d.getElementById('redoEdit').click();assert(w.snapshot().subs[0].text==='光合做用','redo subtitle');
d.getElementById('batchFind').value='做用';d.getElementById('batchReplace').value='作用';d.getElementById('previewReplace').click();assert(w.snapshot().subs[0].text==='光合做用','batch preview does not mutate');d.getElementById('applyBatch').click();assert(w.snapshot().subs[0].text==='光合作用','batch apply changes text');d.getElementById('undoEdit').click();assert(w.snapshot().subs[0].text==='光合做用','undo batch replacement');d.getElementById('redoEdit').click();
d.getElementById('batchOffset').value=-1;d.getElementById('previewShift').click();d.getElementById('applyBatch').click();assert(w.snapshot().subs[0].start===0&&w.snapshot().subs[0].end===1,'subtitle offset clamps to media');
const c=d.getElementById('canvas'),b=c.getBoundingClientRect();d.getElementById('drawTool').value='mosaic';d.getElementById('privacyStart').value=0;d.getElementById('privacyEnd').value=2;d.getElementById('privacyMode').value='solid';c.dispatchEvent(new PointerEvent('pointerdown',{clientX:b.left+b.width*.1,clientY:b.top+b.height*.1,pointerId:1,bubbles:true}));c.dispatchEvent(new PointerEvent('pointermove',{clientX:b.left+b.width*.4,clientY:b.top+b.height*.4,pointerId:1,bubbles:true}));c.dispatchEvent(new PointerEvent('pointerup',{pointerId:1,bubbles:true}));assert(w.snapshot().marks.some(m=>m.tool==='mosaic'&&m.privacyMode==='solid'),'privacy region added');d.getElementById('undoEdit').click();assert(!w.snapshot().marks.length,'undo privacy region');d.getElementById('redoEdit').click();assert(w.snapshot().marks.length===1,'redo privacy region');
await w.saveProject(false);const pid=w.localStorage.getItem('classcast-last-project');await w.restoreProject(pid);assert(w.snapshot().marks[0].tool==='mosaic','privacy survives project restore');assert(d.getElementById('undoEdit').disabled,'history reset at project boundary');
await d.getElementById('checkExport').onclick();assert(d.getElementById('exportChecks').textContent.includes('通過'),'export precheck completes');
d.getElementById('exportEngine').value='worker';await d.getElementById('exportBtn').onclick();assert(!d.getElementById('downloadLink').hidden,'background export completes');const out=await fetch(d.getElementById('downloadLink').href).then(r=>r.blob());const v=document.createElement('video');v.src=URL.createObjectURL(out);await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=rej});assert(v.duration>3&&v.duration<3.4,'background export duration');const pixels=async t=>(await decodedCanvas(out,t)).getContext('2d').getImageData(100,70,1,1).data;let p=await pixels(.5);assert(p[0]<35&&p[2]<60&&p[3]===255,'privacy burned into exported frames');p=await pixels(2.5);assert(p[2]>150,'privacy ends at selected source time');URL.revokeObjectURL(v.src);
const pending=d.getElementById('exportBtn').onclick();d.getElementById('cancelExport').click();await pending;assert(d.getElementById('downloadLink').hidden&&!d.getElementById('exportBtn').disabled,'worker cancellation releases editor');
const row=await w.ClassCastRecovery.begin(media.type);const mid=Math.floor(media.size/2);await w.ClassCastRecovery.append(row,media.slice(0,mid),1,[]);await w.ClassCastRecovery.append(row,media.slice(mid),3.2,w.snapshot().marks);const expected=row.id;await new Promise(res=>{frame.onload=res;frame.src='/?recovery-test=1'});const next=frame.contentWindow;const rows=await next.ClassCastRecovery.list(),saved=rows.find(r=>r.id===expected);assert(saved&&saved.count===2&&!saved.complete,'interrupted recording journal survives reload');const recovered=await next.ClassCastRecovery.blob(saved);assert(recovered.size===media.size,'all journal chunks restored in order');assert(await next.loadVideo(recovered,saved.name,saved.seconds),'recovered media is playable');
results.textContent+='\nALL TEACHING CHECKS PASSED';
}catch(e){results.textContent+='\nFAIL '+e.stack}};
const backgroundButton=document.createElement('button');backgroundButton.textContent='驗證無預覽背景匯出';document.body.prepend(backgroundButton);
backgroundButton.onclick=async()=>{results.textContent='BACKGROUND PREPARING';const w=frame.contentWindow,d=w.document,v=d.getElementById('video'),originalPlay=v.play;try{if(d.getElementById('projects').open)d.getElementById('projects').close();await w.loadVideo(await fixture(),'背景匯出驗證.webm',3.2);d.getElementById('trimStart').value=0;d.getElementById('trimEnd').value=3;for(let i=0;i<10;i++)d.getElementById('addClip').click();const t=v.currentTime;v.play=()=>{throw Error('Background export attempted foreground playback')};frame.style.display='none';results.textContent='BACKGROUND EXPORT RUNNING';await d.getElementById('exportBtn').onclick();assert(!d.getElementById('downloadLink').hidden,'worker exports with hidden preview and playback disabled');assert(v.currentTime===t,'background export never seeks foreground video');const out=await fetch(d.getElementById('downloadLink').href).then(r=>r.blob());const check=document.createElement('video');check.src=URL.createObjectURL(out);await new Promise((resolve,reject)=>{check.onloadedmetadata=resolve;check.onerror=reject});assert(check.duration>29.9&&check.duration<30.2,'all repeated clips encoded in background');URL.revokeObjectURL(check.src);results.textContent+='\nBACKGROUND EXPORT PASSED'}catch(e){results.textContent+='\nFAIL '+e.stack}finally{v.play=originalPlay;frame.style.display=''}};
